const fs = require("fs-extra");
const path = require("path");

const DEFAULT_ENV = `PORT=3000
NODE_ENV=development
`;

const DEFAULT_GITIGNORE = `node_modules/
dist/
.env
*.log
`;

/**
 * Copy a template directory to target and update package.json with projectName.
 * Also generates .env and .gitignore files.
 * @param {string} sourceDir
 * @param {string} targetDir
 * @param {string} projectName (optional) - will override package.json name if present
 * @param {Object} options - { isTypeScript: boolean }
 */
async function copyTemplate(sourceDir, targetDir, projectName, options = {}) {
  try {
    if (!sourceDir || !targetDir) {
      throw new Error("Source and target directories are required.");
    }

    // Ensure source exists
    const exists = await fs.pathExists(sourceDir);
    if (!exists) {
      throw new Error(`Template not found: ${sourceDir}`);
    }

    // Copy
    await fs.copy(sourceDir, targetDir, {
      overwrite: false,
      errorOnExist: true,
    });

    // Try update package.json in the copied template
    const pkgPath = path.join(targetDir, "package.json");
    const pkgExists = await fs.pathExists(pkgPath);
    if (pkgExists && projectName) {
      try {
        const raw = await fs.readFile(pkgPath, "utf8");
        const pkg = JSON.parse(raw);
        // Set sensible defaults for created project
        pkg.name = projectName;
        if (!pkg.version) pkg.version = "0.1.0";
        if (!pkg.description)
          pkg.description = `${projectName} - generated by Kaelum CLI`;
        // Ensure type commonjs by default for templates that expect require/module.exports
        if (!pkg.type) pkg.type = "commonjs";
        await fs.writeFile(pkgPath, JSON.stringify(pkg, null, 2), "utf8");
      } catch (e) {
        // Non-fatal: warn but continue
        console.warn(
          "Warning: failed to update package.json in the template:",
          e.message
        );
      }
    }

    // Generate .env file
    const envPath = path.join(targetDir, ".env");
    const envExists = await fs.pathExists(envPath);
    if (!envExists) {
      await fs.writeFile(envPath, DEFAULT_ENV, "utf8");
    }

    // Generate .gitignore file
    const gitignorePath = path.join(targetDir, ".gitignore");
    const gitignoreExists = await fs.pathExists(gitignorePath);
    if (!gitignoreExists) {
      await fs.writeFile(gitignorePath, DEFAULT_GITIGNORE, "utf8");
    }

    return { ok: true };
  } catch (err) {
    return { ok: false, error: err.message || String(err) };
  }
}

module.exports = { copyTemplate };
